eriskitap/eriskitap/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using eriskitap.Models;
using eriskitap.DAL;
using PagedList;
using System.Globalization;

namespace eriskitap.Controllers
{
    public class HomeController : Controller
    {
        private eriskitapContext db = new eriskitapContext();
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Arama(string arama)
        {
            var items = (from p in db.Uruns where (p.Ad.Contains(arama) || p.Detay.Contains(arama) || p.Kategori.Contains(arama)) orderby p.ID descending select p).ToPagedList(1, 4);
            ViewBag.aranan = arama;
            return View(items);
        }

        [Route("Home/Arama/{arama}/{sayfa}")]
        public ActionResult Arama(string arama, int sayfa)
        {
            var items = (from p in db.Uruns where (p.Ad.Contains(arama) || p.Detay.Contains(arama) || p.Kategori.Contains(arama)) orderby p.ID descending select p).ToPagedList(sayfa, 4);
            ViewBag.aranan = arama;
            return View(items);
        }

        [Route("Urunler/{Kategori}/{sayfa}")]
        public ActionResult Listele(string Kategori, int sayfa = 1)
        {
            ViewBag.Title = Kategori;
            ViewBag.Kategori = Kategori;
            var query = (from p in db.Uruns where (p.Kategori == Kategori) orderby p.ID descending select p).ToPagedList(sayfa, 4);
            return View(query);
        }

        public ActionResult UrunDetay(int id = 0)
        {
            if (id == 0)
            {
                return RedirectToAction("Index");
            }
            Urun urun;
            urun = db.Uruns.Find(id);
            db.SaveChanges();
            return View(urun);
        }
        public ActionResult ChangeCulture(string lang,string returnurl)
        {
            Session["Culture"] = new CultureInfo(lang);
            return Redirect(returnurl);
        }
        public ActionResult index_goster()
        {
            eriskitapContext db = new eriskitapContext();
            List<Urun> urun6 = db.Uruns.OrderByDescending(i => i.ID).Take(3).ToList();
            return PartialView(urun6);
        }
    }
}

eriskitap/eriskitap/Controllers/SepetController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using eriskitap.Models;
using eriskitap.DAL;

namespace eriskitap.Controllers
{
    public class SepetController : Controller
    {
        private eriskitapContext db = new eriskitapContext();
        // GET: Sepet
        public ActionResult Index()
        {
            if (Session["uye_id"] == null)
                return RedirectToAction("GirisYap", "Uyes");
            List<Urun> listeDondur = new List<Urun>();
            if (Session["sepet"] == null)
            {
                return View(listeDondur);
            }
            listeDondur = (List<Urun>)Session["sepet"];
            return View(listeDondur);
        }

        public ActionResult SepetEkle(int id)
        {
            List<Urun> liste = new List<Urun>();
            Urun tmp = db.Uruns.Find(id);
            if (tmp == null)
            {
                return RedirectToAction("Index");
            }
            if (tmp.Adet == 0)
            {
                return Content("<script>alert('Bu üründen stokda kalmamıştır.');window.history.back(-1);</script>", "text/html");
            }
            if (Session["uye_id"] == null)
            {
                RedirectToAction("GirisYap", "Uyes");
            }
            if (Session["sepet"] != null)
                liste.AddRange((List<Urun>)Session["sepet"]);
            liste.Add(tmp);
            Session["sepet"] = liste;
            return RedirectToAction("Index");
        }
        public ActionResult Cikar(int id)
        {
            List<Urun> listeCikar = new List<Urun>();
            listeCikar = (List<Urun>)Session["sepet"];
            Urun tmp = listeCikar.Find(x => x.ID == id);
            if (tmp == null)
            {
                return RedirectToAction("Index");
            }
            listeCikar.Remove(tmp);
            Session["sepet"] = listeCikar;
            return RedirectToAction("Index");
        }
        public ActionResult SatinAl()
        {
            if (Session["uye_id"] == null)
            {
                return RedirectToAction("GirisYap", "Uyes");
            }
            if (Session["sepet"] == null)
            {
                return Content("<script>alert('Sepette satın alınacak ürün bulunmamaktadır.');window.location='/Uyes/Profil';</script>", "text/html");
            }
            List<Urun> listeSil = new List<Urun>();
            listeSil = (List<Urun>)Session["sepet"];
            Urun tmp;
            foreach (var i in listeSil)
            {
                tmp = db.Uruns.Find(i.ID);
                if (tmp.Adet >= 1)
                {
                    tmp.Adet--;
                    db.SaveChanges();
                }
                else
                    continue;
            }
            Session["sepet"] = null;
            return Content("<script>alert('Ürünler satın alındı.');window.location='/Sepet/Index';</script>", "text/html");
        }
    }
}

eriskitap/eriskitap/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

eriskitap/eriskitap/Views/Home/Arama.cshtml
@using PagedList
@using PagedList.Mvc
@model IPagedList<eriskitap.Models.Urun>

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title></title>
</head>
<body>
    <hr />
    <div class="row">
        @if (Model.Count() == 0)
        {
            <div class="row text-center"><h1>Aranan sonuç bulunamadı.</h1></div>
        }
        @foreach (var i in Model)
        {
            <div class="col-sm-4 col-xs-6 col-md-3 text-center">
                <div class="thumbnail">
                    <a href="@Url.Action("UrunDetay/"+@Html.DisplayFor(item => i.ID))"><img src=@Html.DisplayFor(item => i.ResimYol) class="img-responsive" alt="..."></a>
                    <div class="caption">
                        <h3>@Html.DisplayFor(item => i.Ad)</h3>
                        <b>@Html.DisplayFor(item => i.Detay)</b>
                        <p><span class="label label-success">@Html.DisplayFor(item => i.Fiyat) TL</span></p>
                    </div>
                </div>
            </div>
        }
    </div>
    <div class="pagedList row text-center">
        @Html.PagedListPager(Model, sayfa => Url.Action("Arama/" + ViewBag.aranan + "/" + sayfa), PagedListRenderOptions.PageNumbersOnly)
    </div>

</body>
</html>

eriskitap/eriskitap/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

eriskitap/eriskitap/Views/Home/Index.cshtml
@{
    ViewBag.Title = "eriskitap";
}

<hr />
<div class="row">
    <div class="col-md-3 col-xs-12">
        @RenderPage("~/Views/Home/Kategori.cshtml")
        <hr />
    </div>

    <div class="col-md-9 col-xs-12">
        <div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
            <!-- Indicators -->
            <ol class="carousel-indicators">
                <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
                <li data-target="#carousel-example-generic" data-slide-to="1"></li>
                <li data-target="#carousel-example-generic" data-slide-to="2"></li>
            </ol>

            <!-- Wrapper for slides -->
            <div class="carousel-inner">
                <div class="item active">
                    <img src="http://i.dr.com.tr/pimages/Content/Uploads/BannerFiles/dr/1116_d_u_54_851x373_kitaplarla_ugurluyoruz.jpg" width="800" height="600" alt="...">
                    <div class="carousel-caption">
                        
                    </div>
                </div>
                <div class="item">
                    <img src="http://indir.gazetevatan.com/resimler/harry-potter-kitaplari-ibooksta-yayinlandi-6413.jpg" width="800" height="600" alt="...">
                    <div class="carousel-caption">
                        
                    </div>
                </div>
                <div class="item">
                    <img src="http://4.bp.blogspot.com/-oEOPQvuF5xY/VDRHzJJ4GpI/AAAAAAAAG5Q/HocENz507Ks/s1600/20141007_205124.jpg" width="800" height="600" alt="...">
                    <div class="carousel-caption">
                        
                    </div>
                </div>
            </div>

            <!-- Controls -->
            <a class="left carousel-control" href="#carousel-example-generic" role="button" data-slide="prev">
                <span class="glyphicon glyphicon-chevron-left"></span>
            </a>
            <a class="right carousel-control" href="#carousel-example-generic" role="button" data-slide="next">
                <span class="glyphicon glyphicon-chevron-right"></span>
            </a>
        </div>
    </div>
    @Html.Action("index_goster")
</div>

eriskitap/eriskitap/Views/Home/Kategori.cshtml
@{
    ViewBag.Title = "Kategori";
}

<div class="panel-group" id="accordion" >
    <div class ="panel panel-default" style="background-color:lightgreen">
        <div class="panel-heading"style="background-color:lightgreen" >
            <h4 class="panel-title">
                <a href="Urunler/Roman/1">@eriskitap.Resources.lang.Roman</a>
            </h4>
        </div>
    </div>
    <div class="panel panel-default" style="background-color:lightgreen">
        <div class="panel-heading" style="background-color:lightgreen">
            <h4 class="panel-title">
                <a href="Urunler/Edebiyat/1">@eriskitap.Resources.lang.Edebiyat</a>
            </h4>
        </div>
    </div>
    <div class="panel panel-default" style="background-color:lightgreen">
        <div class="panel-heading" style="background-color:lightgreen">
            <h4 class="panel-title">
                <a href="Urunler/Şiir/1">@eriskitap.Resources.lang.Şiir</a>
            </h4>
        </div>
    </div>
    <div class="panel panel-default" style="background-color:lightgreen">
        <div class="panel-heading" style="background-color:lightgreen">
            <h4 class="panel-title">
                <a href="Urunler/Tarih/1">@eriskitap.Resources.lang.Tarih</a>
            </h4>
        </div>

    </div>
</div>

eriskitap/eriskitap/Views/Home/Listele.cshtml
@using PagedList
@using PagedList.Mvc
@model IPagedList<eriskitap.Models.Urun>
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title></title>
</head>
<body>
    <hr />
    <div class="row">
        @if (Model.Count() == 0)
        {
            <div class="row text-center"><h1>@eriskitap.Resources.lang.BuKategorideUrunYok</h1></div>
        }


        @foreach (var i in Model)
        {
            <div class="col-sm-4 col-xs-6 col-md-3 text-center">
                <div class="thumbnail">
                    <a href="@Url.Action("UrunDetay/"+@Html.DisplayFor(item => i.ID))"><img src=@Html.DisplayFor(item => i.ResimYol) class="img-responsive" alt="..." width="150" height="200"></a>
                    <div class="caption">
                        <h4>@Html.DisplayFor(item => i.Ad)</h4>
                        <p>@Html.DisplayFor(item => i.Detay)</p>
                        <p><span class="label label-success">@Html.DisplayFor(item => i.Fiyat) TL</span></p>
                    </div>
                </div>
            </div>
        }
    </div>
    <div class="pagedList row text-center">
        @Html.PagedListPager(Model, sayfa => Url.Action(ViewBag.Cinsiyet + "/" + ViewBag.Kategori + "/" + sayfa, "Urunler"), PagedListRenderOptions.PageNumbersOnly)
    </div>
</body>
</html>

eriskitap/eriskitap/Views/Home/UrunDetay.cshtml
@model eriskitap.Models.Urun

@{
    ViewBag.Title = @Html.DisplayFor(model => model.Ad) + " - " + @Html.DisplayFor(model => model.Detay);
}

<div class="row text-center">
    <div class="col-md-5">
        <img src="@Html.DisplayFor(model => model.ResimYol)" class="img-responsive" />
    </div>
    <div class="col-md-7">
        <p><h1 class="text-primary"><b>@Html.DisplayFor(model => Model.Ad)</b></h1></p>
        <p><h4>@Html.DisplayFor(model => Model.Detay)</h4></p>
        <p><h4 class="text-success">@Html.DisplayFor(model => Model.Fiyat) TL</h4></p>
        <p><a href="@Url.Action("SepetEkle/" + @Html.DisplayFor(model => model.ID),"Sepet")" class="btn btn-success">Sepete Ekle</a></p>
    </div>
</div>

eriskitap/eriskitap/Views/Home/index_goster.cshtml
@model List<eriskitap.Models.Urun>

<hr />
<br />
<div class="row">
    @{
        foreach (var item in Model)
        {

            <div class="col-sm-4 col-lg-4 col-md-4">
                <div class="thumbnail">
                    <img src=@item.ResimYol alt="" href="Urunler/@item.Kategori/1" style="width:200px;height:150px">
                    <div class="caption">
                        <h4 class="pull-right">@item.Fiyat ₺</h4>
                        <h4>
                            <a href="Urunler/@item.Kategori/1">@item.Ad-@item.Detay</a>
                        </h4>
                    </div>
                </div>
            </div>
        }
    }

</div>